services:
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
    command: npm run test
    environment:
      - DATABASE_HOST=db
      - DATABASE_DB=base
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - NODE_ENV=development
    ports:
      - 80:80
    secrets:
      - db-password
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    secrets:
      - db-password
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=base
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:7000
    networks:
      - public
      - private
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt
